const enum ROUTES {
    MAIN_APP = 'MAIN_APP',
    MAIN_NAVIGATOR = 'MAIN_NAVIGATOR',

    HOME = 'HOME',
    SEARCH = 'SEARCH',
    PROFILE = 'PROFILE',

    MOVIE_DETAIL = 'MOVIE_DETAIL'
}

export default ROUTES
